export type RideRouteQualityStatus = 'FULL' | 'PARTIAL' | 'REJECTED';

export const RIDE_ROUTE_QUALITY_REJECTED_ERROR_CODE = 'RIDE_ROUTE_QUALITY_REJECTED';
export const RIDE_ROUTE_QUALITY_UNVERIFIED_ERROR_CODE = 'RIDE_ROUTE_QUALITY_UNVERIFIED';
